version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3333:3333
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080