# Generated by Django 4.2.7 on 2023-12-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCustomer',
            fields=[
                ('customer_key', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('loyal_group', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=10)),
                ('yearly_income', models.IntegerField()),
                ('total_children', models.IntegerField(null=True)),
                ('is_active', models.IntegerField()),
                ('customer_since', models.CharField(max_length=10)),
                ('recency', models.IntegerField(null=True)),
                ('frequency', models.DecimalField(decimal_places=8, max_digits=20)),
                ('monetary', models.IntegerField()),
                ('monetary_m', models.DecimalField(db_column='monetary_m_', decimal_places=6, max_digits=20)),
                ('rfm', models.IntegerField()),
                ('segment', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detail_customer',
            },
        ),
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_key', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('loyal_group', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
                ('yearly_income', models.IntegerField()),
                ('total_children', models.IntegerField(null=True)),
                ('is_active', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'dim_customer',
            },
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('product_key', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=60)),
                ('product_category', models.CharField(max_length=30)),
                ('product_subcategory', models.CharField(max_length=30)),
                ('uom', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=40)),
                ('suplier_name', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=10, null=True)),
                ('uom_weight', models.CharField(max_length=10, null=True)),
                ('volume', models.CharField(max_length=10, null=True)),
                ('uom_volumn', models.CharField(max_length=10, null=True)),
                ('length', models.CharField(max_length=10, null=True)),
                ('width', models.CharField(max_length=10, null=True)),
                ('heigth', models.CharField(max_length=10, null=True)),
                ('uom_size', models.CharField(max_length=10, null=True)),
                ('link', models.CharField(max_length=190)),
                ('product_category_image', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'dim_product',
            },
        ),
        migrations.CreateModel(
            name='DimStore',
            fields=[
                ('store_key', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=40)),
                ('manager', models.CharField(max_length=20)),
                ('manager_image', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=110)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=20)),
            ],
            options={
                'db_table': 'dim_store',
            },
        ),
        migrations.CreateModel(
            name='FactEcommerceSales',
            fields=[
                ('order_key', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=30)),
                ('order_line_number', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_time', models.CharField(max_length=20)),
                ('customer_key', models.IntegerField()),
                ('channel_name', models.CharField(max_length=10)),
                ('store_key', models.IntegerField()),
                ('product_key', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('total_sale', models.IntegerField()),
            ],
            options={
                'db_table': 'fact_ecommerce_sales',
            },
        ),
    ]
